language: go

sudo: false

before_script:
  - go vet ./...

install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

script:
  - go build .
  - go test -timeout 1s -cpu=2 -race -v ./...
  - go test -timeout 1s -cpu=2 -covermode=atomic ./...
